### ISSUE TITLE
Nebula bench supports offline install mode and ldbc-snb test case

### ISSUE THREAD

**Issue by lcqzte10192193** [nebula-contrib/NebulaGraph-Bench#44]
Hi~
Recently，I tested nebula graph using nebula bench.Since our server can not connect to the internet，we must prepare ldbc test data first in another server ,then build k6 plugin and nebula importer using offline mode. This is a waste of time. 
I have used tiger graph and Neo4j.They have supported ldbc-snb，include IS、IC and BI queries， but nebula support only a few part. It‘s not convenient for users to compare Nebula with other graph db.

**Comment by HarrisChu** [comment]
Q1:

https://github.com/vesoft-inc/nebula-bench/issues/40
we would refactor with golang, and then uses can download the binary directly, but no plan yet.

Q2:
Good point, we just support Interactive now, we should support BI in future.

**Comment by lcqzte10192193** [comment]
Hi HarrisChu，
You said nebula-bench support interactive now, When will this feature be released to github?  Now I only find three scenarios-- findshortest、GoNStep and Insert.

**Comment by HarrisChu** [comment]
> Hi HarrisChu，
> You said nebula-bench support interactive now, When will this feature be released to github? Now I only find three scenarios-- findshortest、GoNStep and Insert.

sorry for misunderstanding, I mean we support Interactive data, i.g. import into nebula automaticly.
and you can write `short read`, `complex read` queries for yourself.

**Comment by lcqzte10192193** [comment]
OK, Thank you for your replay.

**Comment by HarrisChu** [comment]
btw, if you want to run some case manually, you can use k6 https://github.com/vesoft-inc/k6-plugin

nebula-bench just render k6 scripts automatically, and you can modify it in your scenarios.
